### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 84: character maps to <undefined>

### ISSUE THREAD

**Issue by llw2021** [boeboe/china-cities#1]
Getting an Unicode decoded error when I tried to import the china_cities python. Any advices?

**Comment by wangzhaojin66** [comment]
Try encoding='utf-8' in the open method at line 22 of the china_cities/cities.py file

**Comment by wangzhaojin66** [comment]
with open(os.path.join(__location__, 'cities.csv'), encoding='utf-8') as fileHandler:
    for line in fileHandler:
        split = line.strip().split(",")
        CITIES.append(City(name_en=split[0], name_cn=split[1], province=split[2]))

**Comment by boeboe** [comment]
Fixed in 0.0.4 (only python3)
